/*
 * This file is generated by jOOQ.
 */
package cc.phonecard.jooq.tables.records;


import cc.phonecard.jooq.tables.Books;
import cc.phonecard.jooq.tables.interfaces.IBooks;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BooksRecord extends UpdatableRecordImpl<BooksRecord> implements VertxPojo, Record6<Integer, Integer, String, String, String, LocalDateTime>, IBooks {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>books.id</code>.
     */
    @Override
    public BooksRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>books.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>books.channel_id</code>.
     */
    @Override
    public BooksRecord setChannelId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>books.channel_id</code>.
     */
    @Override
    public Integer getChannelId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>books.order_no</code>.
     */
    @Override
    public BooksRecord setOrderNo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>books.order_no</code>.
     */
    @Override
    public String getOrderNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>books.phone_num</code>.
     */
    @Override
    public BooksRecord setPhoneNum(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>books.phone_num</code>.
     */
    @Override
    public String getPhoneNum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>books.create_time</code>.
     */
    @Override
    public BooksRecord setCreateTime(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>books.create_time</code>.
     */
    @Override
    public String getCreateTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>books.update_time</code>.
     */
    @Override
    public BooksRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>books.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Books.BOOKS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Books.BOOKS.CHANNEL_ID;
    }

    @Override
    public Field<String> field3() {
        return Books.BOOKS.ORDER_NO;
    }

    @Override
    public Field<String> field4() {
        return Books.BOOKS.PHONE_NUM;
    }

    @Override
    public Field<String> field5() {
        return Books.BOOKS.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Books.BOOKS.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getChannelId();
    }

    @Override
    public String component3() {
        return getOrderNo();
    }

    @Override
    public String component4() {
        return getPhoneNum();
    }

    @Override
    public String component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getChannelId();
    }

    @Override
    public String value3() {
        return getOrderNo();
    }

    @Override
    public String value4() {
        return getPhoneNum();
    }

    @Override
    public String value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public BooksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BooksRecord value2(Integer value) {
        setChannelId(value);
        return this;
    }

    @Override
    public BooksRecord value3(String value) {
        setOrderNo(value);
        return this;
    }

    @Override
    public BooksRecord value4(String value) {
        setPhoneNum(value);
        return this;
    }

    @Override
    public BooksRecord value5(String value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public BooksRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public BooksRecord values(Integer value1, Integer value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBooks from) {
        setId(from.getId());
        setChannelId(from.getChannelId());
        setOrderNo(from.getOrderNo());
        setPhoneNum(from.getPhoneNum());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IBooks> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(Books.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(Integer id, Integer channelId, String orderNo, String phoneNum, String createTime, LocalDateTime updateTime) {
        super(Books.BOOKS);

        setId(id);
        setChannelId(channelId);
        setOrderNo(orderNo);
        setPhoneNum(phoneNum);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(cc.phonecard.jooq.tables.pojos.Books value) {
        super(Books.BOOKS);

        if (value != null) {
            setId(value.getId());
            setChannelId(value.getChannelId());
            setOrderNo(value.getOrderNo());
            setPhoneNum(value.getPhoneNum());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
        }
    }

        public BooksRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
