/*
 * This file is generated by jOOQ.
 */
package cc.phonecard.jooq;


import cc.phonecard.jooq.tables.Books;
import cc.phonecard.jooq.tables.records.BooksRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BooksRecord> BOOKS__PK_BOOKS = Internal.createUniqueKey(Books.BOOKS, DSL.name("pk_books"), new TableField[] { Books.BOOKS.ID }, true);
    public static final UniqueKey<BooksRecord> BOOKS__UK_BOOKS_112182427 = Internal.createUniqueKey(Books.BOOKS, DSL.name("uk_books_112182427"), new TableField[] { Books.BOOKS.PHONE_NUM }, true);
}
