/*
 * This file is generated by jOOQ.
 */
package cc.phonecard.jooq;


import cc.phonecard.jooq.tables.Books;
import cc.phonecard.jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
