/*
 * This file is generated by jOOQ.
 */
package cc.phonecard.jooq.tables.pojos;


import cc.phonecard.jooq.tables.interfaces.IBooks;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Books implements VertxPojo, IBooks {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer channelId;
    private String orderNo;
    private String phoneNum;
    private String createTime;
    private LocalDateTime updateTime;

    public Books() {}

    public Books(IBooks value) {
        this.id = value.getId();
        this.channelId = value.getChannelId();
        this.orderNo = value.getOrderNo();
        this.phoneNum = value.getPhoneNum();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public Books(
        Integer id,
        Integer channelId,
        String orderNo,
        String phoneNum,
        String createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.channelId = channelId;
        this.orderNo = orderNo;
        this.phoneNum = phoneNum;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

        public Books(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>books.id</code>.
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>books.id</code>.
     */
    @Override
    public Books setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>books.channel_id</code>.
     */
    @Override
    public Integer getChannelId() {
        return this.channelId;
    }

    /**
     * Setter for <code>books.channel_id</code>.
     */
    @Override
    public Books setChannelId(Integer channelId) {
        this.channelId = channelId;
        return this;
    }

    /**
     * Getter for <code>books.order_no</code>.
     */
    @Override
    public String getOrderNo() {
        return this.orderNo;
    }

    /**
     * Setter for <code>books.order_no</code>.
     */
    @Override
    public Books setOrderNo(String orderNo) {
        this.orderNo = orderNo;
        return this;
    }

    /**
     * Getter for <code>books.phone_num</code>.
     */
    @Override
    public String getPhoneNum() {
        return this.phoneNum;
    }

    /**
     * Setter for <code>books.phone_num</code>.
     */
    @Override
    public Books setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
        return this;
    }

    /**
     * Getter for <code>books.create_time</code>.
     */
    @Override
    public String getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>books.create_time</code>.
     */
    @Override
    public Books setCreateTime(String createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * Getter for <code>books.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>books.update_time</code>.
     */
    @Override
    public Books setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Books other = (Books) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.channelId == null) {
            if (other.channelId != null)
                return false;
        }
        else if (!this.channelId.equals(other.channelId))
            return false;
        if (this.orderNo == null) {
            if (other.orderNo != null)
                return false;
        }
        else if (!this.orderNo.equals(other.orderNo))
            return false;
        if (this.phoneNum == null) {
            if (other.phoneNum != null)
                return false;
        }
        else if (!this.phoneNum.equals(other.phoneNum))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.channelId == null) ? 0 : this.channelId.hashCode());
        result = prime * result + ((this.orderNo == null) ? 0 : this.orderNo.hashCode());
        result = prime * result + ((this.phoneNum == null) ? 0 : this.phoneNum.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Books (");

        sb.append(id);
        sb.append(", ").append(channelId);
        sb.append(", ").append(orderNo);
        sb.append(", ").append(phoneNum);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBooks from) {
        setId(from.getId());
        setChannelId(from.getChannelId());
        setOrderNo(from.getOrderNo());
        setPhoneNum(from.getPhoneNum());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IBooks> E into(E into) {
        into.from(this);
        return into;
    }
}
