/*
 * This file is generated by jOOQ.
 */
package cc.phonecard.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBooks extends VertxPojo, Serializable {

    /**
     * Setter for <code>books.id</code>.
     */
    public IBooks setId(Integer value);

    /**
     * Getter for <code>books.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>books.channel_id</code>.
     */
    public IBooks setChannelId(Integer value);

    /**
     * Getter for <code>books.channel_id</code>.
     */
    public Integer getChannelId();

    /**
     * Setter for <code>books.order_no</code>.
     */
    public IBooks setOrderNo(String value);

    /**
     * Getter for <code>books.order_no</code>.
     */
    public String getOrderNo();

    /**
     * Setter for <code>books.phone_num</code>.
     */
    public IBooks setPhoneNum(String value);

    /**
     * Getter for <code>books.phone_num</code>.
     */
    public String getPhoneNum();

    /**
     * Setter for <code>books.create_time</code>.
     */
    public IBooks setCreateTime(String value);

    /**
     * Getter for <code>books.create_time</code>.
     */
    public String getCreateTime();

    /**
     * Setter for <code>books.update_time</code>.
     */
    public IBooks setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>books.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IBooks
     */
    public void from(IBooks from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IBooks
     */
    public <E extends IBooks> E into(E into);

        @Override
        public default IBooks fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getInteger,"id","java.lang.Integer");
                setOrThrow(this::setChannelId,json::getInteger,"channel_id","java.lang.Integer");
                setOrThrow(this::setOrderNo,json::getString,"order_no","java.lang.String");
                setOrThrow(this::setPhoneNum,json::getString,"phone_num","java.lang.String");
                setOrThrow(this::setCreateTime,json::getString,"create_time","java.lang.String");
                setOrThrow(this::setUpdateTime,key -> {String s = json.getString(key); return s==null?null: LocalDateTime.parse(s);},"update_time","java.time.LocalDateTime");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("channel_id",getChannelId());
                json.put("order_no",getOrderNo());
                json.put("phone_num",getPhoneNum());
                json.put("create_time",getCreateTime());
                json.put("update_time",getUpdateTime()==null?null:getUpdateTime().toString());
                return json;
        }

}
